### ISSUE TITLE
Server crashes on join if mod loaded

### ISSUE THREAD

**Issue by jimmy927** [anviaan/Record-Days-Survived#2]
```
- minecraft@hzdocker2:~/fabric$ java -Xmx2G -jar fabric-server-mc.1.20.1-loader.0.14.22-launcher.0.11.2.jar nogui
- Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
- [21:27:18] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
- [21:27:18] [main/INFO]: Loading 45 mods:
-         - fabric-api 0.88.1+1.20.1
-            |-- fabric-api-base 0.4.30+7abfd51577
-            |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
-            |-- fabric-biome-api-v1 13.0.10+b3afc78b77
-            |-- fabric-block-api-v1 1.0.10+92a0d36777
-            |-- fabric-block-view-api-v2 1.0.0+92a0d36777
-            |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
-            |-- fabric-client-tags-api-v1 1.1.1+97bb207577
-            |-- fabric-command-api-v1 1.2.33+f71b366f77
-            |-- fabric-command-api-v2 2.2.12+b3afc78b77
-            |-- fabric-commands-v0 0.2.50+df3654b377
-            |-- fabric-containers-v0 0.1.63+df3654b377
-            |-- fabric-content-registries-v0 4.0.9+b3afc78b77
-            |-- fabric-convention-tags-v1 1.5.4+a1a980da77
-            |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
-            |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
-            |-- fabric-dimensions-v1 2.1.53+8536527b77
-            |-- fabric-entity-events-v1 1.5.22+b3afc78b77
-            |-- fabric-events-interaction-v0 0.6.1+e91849a877
-            |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
-            |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
-            |-- fabric-item-api-v1 2.1.27+b3afc78b77
-            |-- fabric-item-group-api-v1 4.0.10+23d9108177
-            |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
-            |-- fabric-keybindings-v0 0.2.34+df3654b377
-            |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
-            |-- fabric-loot-api-v2 1.1.39+b3afc78b77
-            |-- fabric-loot-tables-v1 1.1.43+9e7660c677
-            |-- fabric-message-api-v1 5.1.7+3265161977
-            |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
-            |-- fabric-model-loading-api-v1 1.0.2+709a987177
-            |-- fabric-models-v0 0.4.1+9386d8a777
-            |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
-            |-- fabric-networking-v0 0.3.50+df3654b377
-            |-- fabric-object-builder-api-v1 11.1.1+6beca84877
-            |-- fabric-particles-v1 1.1.1+201a23a077
-            |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
-            |-- fabric-registry-sync-v0 2.3.2+4df89eb277
-            |-- fabric-renderer-api-v1 3.1.3+92a0d36777
-            |-- fabric-renderer-indigo 1.4.3+6bdb2ed077
-            |-- fabric-renderer-registries-v1 3.2.45+df3654b377
-            |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
-            |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
-            |-- fabric-rendering-v0 1.1.48+df3654b377
-            |-- fabric-rendering-v1 3.0.7+b3afc78b77
-            |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
-            |-- fabric-resource-loader-v0 0.11.9+132c48c177
-            |-- fabric-screen-api-v1 2.0.7+b3afc78b77
-            |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
-            |-- fabric-sound-api-v1 1.0.12+b3afc78b77
-            |-- fabric-transfer-api-v1 3.3.1+195226a777
-            \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
-         - fabricloader 0.14.22
-         - java 17
-         - minecraft 1.20.1
-         - record_days_survived 2.0
-            |-- cardinal-components-base 5.2.2
-            \-- cardinal-components-entity 5.2.2
- [21:27:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/minecraft/fabric/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
- [21:27:18] [main/INFO]: Compatibility level set to JAVA_16
- [21:27:18] [main/INFO]: Compatibility level set to JAVA_17
- [21:27:18] [main/WARN]: Reference map '(Fabric)RecordDaySurvived-1.20-refmap.json' for record_days_survived.mixins.json could not be read. If this is a development environment you can ignore this message
- [21:27:23] [main/INFO]: Record Days Survived mod initialized!
- [21:27:23] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
- [21:27:24] [main/INFO]: Loaded 7 recipes
- [21:27:24] [main/INFO]: Loaded 1271 advancements
- [21:27:24] [main/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.422 ms
- [21:27:24] [Server thread/INFO]: Starting minecraft server version 1.20.1
- [21:27:24] [Server thread/INFO]: Loading properties
- [21:27:24] [Server thread/INFO]: Default game type: SURVIVAL
- [21:27:24] [Server thread/INFO]: Generating keypair
- [21:27:24] [Server thread/INFO]: Starting Minecraft server on *:25565
- [21:27:24] [Server thread/INFO]: Using epoll channel type
- [21:27:24] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
- [21:27:24] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
- [21:27:24] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
- [21:27:24] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
- [21:27:24] [Server thread/INFO]: Preparing level "world"
- [21:27:25] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
- [21:27:26] [Worker-Main-19/INFO]: Preparing spawn area: 0%
- [21:27:26] [Worker-Main-6/INFO]: Preparing spawn area: 0%
- [21:27:26] [Worker-Main-33/INFO]: Preparing spawn area: 0%
- [21:27:26] [Worker-Main-6/INFO]: Preparing spawn area: 0%
- [21:27:27] [Worker-Main-36/INFO]: Preparing spawn area: 0%
- [21:27:27] [Worker-Main-23/INFO]: Preparing spawn area: 40%
- [21:27:28] [Server thread/INFO]: Time elapsed: 2924 ms
- [21:27:28] [Server thread/INFO]: Done (3.335s)! For help, type "help"
- [21:28:04] [Server thread/INFO]: jimmy927b[/79.136.63.202:62521] logged in with entity id 200 at (-46.5, 103.0, 75.5)
- [21:28:04] [Server thread/INFO]: jimmy927b joined the game
- [21:28:04] [Server thread/ERROR]: Encountered an unexpected exception
- java.lang.NoClassDefFoundError: net/minecraft/class_1074
-         at net.anvian.record_days_survived.command.RecordCommand.lambda$reportDay$1(RecordCommand.java:48) ~[Fabric-RecordDaySurvived-1.20.2-2.0.jar:?]
-         at net.minecraft.class_2168.method_9226(class_2168.java:321) ~[server-intermediary.jar:?]
-         at net.anvian.record_days_survived.command.RecordCommand.reportDay(RecordCommand.java:51) ~[Fabric-RecordDaySurvived-1.20.2-2.0.jar:?]
-         at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
-         at net.minecraft.class_2170.method_9249(class_2170.java:287) ~[server-intermediary.jar:?]
-         at net.minecraft.class_2170.method_44252(class_2170.java:280) ~[server-intermediary.jar:?]
-         at net.anvian.record_days_survived.RecordDaysSurvivedMod.lambda$onInitialize$1(RecordDaysSurvivedMod.java:38) ~[Fabric-RecordDaySurvived-1.20.2-2.0.jar:?]
-         at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:39) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-d192667b6fe65399.jar:?]
-         at net.minecraft.class_3218$class_5526.handler$zdg000$fabric-lifecycle-events-v1$invokeEntityLoadEvent(class_3218.java:1696) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1577) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1536) ~[server-intermediary.jar:?]
-         at net.minecraft.class_5579.method_31847(class_5579.java:216) ~[server-intermediary.jar:?]
-         at net.minecraft.class_5579.method_31820(class_5579.java:186) ~[server-intermediary.jar:?]
-         at net.minecraft.class_5579.method_31818(class_5579.java:167) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3218.method_18771(class_3218.java:902) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3218.method_18213(class_3218.java:888) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3324.method_14570(class_3324.java:261) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3248.redirect$zed000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
-         at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
-         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
-         at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
-         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
-         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
-         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
-         at java.lang.Thread.run(Thread.java:833) ~[?:?]
- Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1074
-         at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
-         at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
-         at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.22.jar:?]
-         at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
-         at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
-         ... 29 more
- [21:28:04] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/fabric/./crash-reports/crash-2023-09-16_21.28.04-server.txt
- [21:28:04] [Server thread/INFO]: Stopping server
- [21:28:04] [Server thread/INFO]: Saving players
- [21:28:04] [Server thread/INFO]: Saving worlds
- [21:28:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
- [21:28:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
- [21:28:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
- [21:28:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
- [21:28:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
- [21:28:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
- [21:28:06] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
- minecraft@hzdocker2:~/fabric$ 
```

**Comment by anviaan** [comment]
fixed
